project:
  type: website

website:
  title: "Pilot DB with Mareano"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "DB Design"
        menu:
          - text: "DB Schema"
            href: db-schema.qmd
          - text: "Incorrect Data"
            href: incorrect-data.qmd
      - text: "Distance to Coast"
        menu:
          - text: "Distance Calculation"
            href: distance-to-coast.qmd
          - text: "Interactive Map"
            href: distance-interactive-map.qmd
      - text: "Data Export"
        href: data-export.qmd

format:
  html:
    include-in-header: header.html
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    df-print: kable

execute:
  echo: false
  warning: false
  message: false
